* Contextual Profile Management System

Contextual is a profile management system for GNU Emacs. A profile is made up by
an arbitrary number of global variables that influence how Emacs behaves, as
well as custom code. Upon switching profiles, the variables are adapted and the
custom profile code is run, if present.
Typical use cases for such profiles are user identifying variables such as
=user-mail-address= or =epg-user-id= which need to be changed when using the
same instance of Emacs for private and professional purposes.
Other use cases can, for instance, involve switching to different themes or
fonts to adapt to different screens of light conditions.

* Installation

Contextual is available via ELPA, from the [[https://github.com/milkypostman/melpa#usage][MELPA repository]].
Running =M-x package-install RET contextual RET= is usually the quickest way to
retrieve Contextual, given that MELPA has been made available as a package
repository.

* Usage

Contextual can be used in two ways: Through its default profile group and
through custom profile groups, which can be used independently from each
other. A profile group consists of a list of profiles to switch between, as well
as meta data.

** Basic setup

Basic setup consists of the following steps:
1. Loading Contextual
2. Adding one or more profiles
3. (optional, recommended) specifying an initial profile to load
4. Activating Contextual

#+BEGIN_SRC emacs-lisp
  (require 'contextual)

  (ctx-add-profile "private" ()
    ((user-mail-address "john@doe.name")
     (epg-user-id "1234ABCD")))

  (ctx-add-profile "work" ()
    ((user-mail-address "jdoe@megacorp.inc")
     (epg-user-id "5678EFGH")))

  (ctx-set-initial-profile "private")

  (contextual-global-mode) ; activates the initial profile right away
#+END_SRC

Switching between profiles in the default profile group is bound to
=ctx-load-profile=, or =c= in the Contextual prefix map. The default prefix for
Contextual is =C-c c=, so the default key combination is
=C-c c c=. Contextual provides completion candidates and is therefore
compatible with completion framework such as HELM.

Contextual minor mode is indicated in the mode line by =ctx= followed by the
currently active profile name in brackets, e.g. =ctx[private]=.

The keymap prefix =C-c c= can be changed by setting =ctx-keymap-prefix=:

#+BEGIN_SRC emacs-lisp
  (setq ctx-keymap-prefix (kbd "..."))
#+END_SRC

** Custom profile groups

Defining custom profile groups is useful to define variables to be used
independently from the default profile group. The following example defines
profiles for different font sizes, which needs custom code to be run.

#+BEGIN_SRC emacs-lisp
  (ctx-define-profiles font-profiles "normal")

  (ctx-add-profile "small" (font-profiles) ((default-frame-alist ((font . "Inconsolata-6"))))
    (set-frame-font "Inconsolata-6"))
  (ctx-add-profile "normal" (font-profiles) ((default-frame-alist ((font . "Inconsolata-9"))))
    (set-frame-font "Inconsolata-9"))

  (ctx-define-profile-loader font-profile-loader
    font-profiles (kbd "f"))
#+END_SRC

The first form binds a new variable =font-profiles= with an initial profile
of =normal=. =ctx-add-profile= takes the profile group as an optional parameter
in the first pair of parens. Without the parameter, the profiles would instead
be added to the default profile group. =set-frame-font= is run every time the
respective profile is being activated.

=ctx-define-profile-loader= binds a new interactive function for a profile
group and assigns it a key in Contextual's keymap. Here, =font-profile-loader=
is the name of the new symbol to bind the loader to, =font-profiles= was defined
earlier and =(kbd "f")= specifies the key to bind to.

After running this code, the =normal= font profile would automatically be
preloaded and =M-x font-profile-loader RET= or =C-c c f= can
be used to switch between font profiles.

** API
The public part of the API which can be used safely as long as the major version
of the package doesn't change is comprised of the following functions:

- =ctx-add-profile NAME (&optional (PROFILES 'ctx-default-profiles)) (&rest VARS) &rest BODY=
- =ctx-set-initial-profile NAME=
- =ctx-define-profiles NAME &optional INITIAL=
- =ctx-define-profile-loader NAME GROUP &optional KEY=
- =contextual-global-mode=

Additional functions that may be of use but which are not guaranteed to be
stable are:

- =ctx-reset-profiles PROFILES=
- =ctx-activate-profile GROUP NAME=

** Copyright

Copyright © 2016 LShift Services GmbH

Contextual is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

statehack is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
